# Generated by Django 5.1.5 on 2025-01-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/profile.png', upload_to='profile_pictures/'),
        ),
    ]
