# Generated by Django 5.1.5 on 2025-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
