# Generated by Django 5.1.5 on 2025-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_expected_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('accessories', 'Accessories & Gadgets'), ('smartphones', 'Smartphones & Accessories'), ('laptops', 'Laptops & Computers'), ('tv_entertainment', 'TVs & Home Entertainment'), ('audio', 'Audio & Headphones'), ('gaming', 'Gaming & Accessories'), ('cameras', 'Cameras & Photography'), ('wearables', 'Wearables & Smartwatches'), ('home_appliances', 'Home Appliances'), ('networking', 'Networking & Internet'), ('power', 'Power & Batteries'), ('drones', 'Drones & RC Gadgets'), ('diy', 'DIY Electronics & Components'), ('office', 'Office & Stationery Tech'), ('car_electronics', 'Car Electronics'), ('security', 'Security & Surveillance'), ('software', 'Software & Apps'), ('other', 'Other Electronics')], default='accessories', max_length=50),
        ),
    ]
