# Generated by Django 5.1.5 on 2025-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CEO', 'CEO & Founder'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('DEV', 'Software Developer'), ('DESIGNER', 'UI/UX Designer'), ('SUPPORT', 'Customer Support')], default='DEV', max_length=20)),
                ('image', models.ImageField(upload_to='team_images/')),
            ],
        ),
    ]
