# Generated by Django 5.1.5 on 2025-02-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_approved',
        ),
        migrations.AddField(
            model_name='order',
            name='derivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
    ]
