# Generated by Django 5.1.5 on 2025-02-04 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_derivery_status_order_delivery_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commented_products', through='store.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
