# Generated by Django 5.1.5 on 2025-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_notification_for_all_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO & Founder'), ('CTO', 'Chief Technology Officer'), ('CMO', 'Chief Marketing Officer'), ('DEV', 'Software Developer'), ('DESIGNER', 'UI/UX Designer'), ('SUPPORT', 'Customer Support'), ('agent', 'Agent'), ('MARKETING', 'Marketing Specialist'), ('HR', 'Human Resource Manager'), ('FINANCE', 'Finance Manager'), ('OTHER', 'Other')], default='DEV', max_length=20),
        ),
    ]
