# Generated by Django 5.1.5 on 2025-02-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_teammember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
